config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    flash[:notice] = 'Kitten created'

    if @kitten.save
      redirect_to @kitten
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    flash[:notice] = 'Kitten updated'

    if @kitten.update(kitten_params)
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy!
    flash[:notice] = 'Kitten deleted'

    redirect_to root_path
  end

  private

  def kitten_params
    params.expect(kitten: %i[name age cuteness softness])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |f| %>
  <% if kitten.errors.any? %>
    <div style="color: red">
      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <br>
  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>
  <br>
  <%= f.label :softness %>
  <%= f.text_field :softness %>
  <br>
  <%= f.submit %>
<% end %>

app/views/kittens/_kitten.html.erb
<div id="<%= kitten.id %>">
    <h3><%= kitten.name %></h3>
    <p>
        Age: <%= kitten.age %>
        <br>
        Cuteness: <%= kitten.cuteness %>
        <br>
        Softness: <%= kitten.softness %>
    </p>
    <%= link_to 'Edit kitten', edit_kitten_path(kitten.id) %>
    <%= button_to 'Delete kitten', kitten, method: :delete %>
</div>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render 'form', kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>Kitten List</h1>
<% @kittens.each do |kitten| %>
    <%= link_to 'Add new kitten', new_kitten_path %>
    <%= render kitten %>
<% end %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<%= render 'kitten', kitten: @kitten %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>